# -*- coding: utf-8 -*-
"""Detransform_forecast.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ws42_tMbx07bUQ5ZuyWoqvBgqvZtkP0S
"""

#Detransform the differencing in order to set the forecast to the original scale
def detransform(X_train, X_test, second_diff=False):
    """Revert back the differencing to get the forecast to original scale."""
    forecast = X_test.copy()
    columns = X_train.columns
    for column in columns:        
        if second_diff:
            Xtest[str(column)+'_1d'] = (X_train[column].iloc[-1]-X_train[column].iloc[-2]) + Xtest[str(column)+'_2d'].cumsum()
  
        Xtest[str(column)+'_forecast'] = X_train[column].iloc[-1] + Xtest[str(column)+'_1d'].cumsum()
    return forecast